package:
  name: lasersdk
  version: "1.2.0"

source:
  url: https://files.pythonhosted.org/packages/a6/67/96a792ddbc8b620ea050ef8df9ee8e30a7500dfe9d21b44dbaf7bdec39bd/toptica_lasersdk-1.2.0-py3-none-any.whl
  sha256: 3ce7c6b69584172fd0738cb53c2c9db2b4432a1df9b328200eb0d7e05b870890

build:
  noarch: python
  number: 1
  script: pip install --no-deps toptica_lasersdk-1.2.0-py3-none-any.whl

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyserial

test:
  imports:
    - toptica.lasersdk.client
    - toptica.lasersdk.async.client

about:
  home: https://toptica.github.io/python-lasersdk
  license: MIT
  summary: Control TOPTICA laser products
